services:
  - type: web
    name: tp01-fruhauf-ewan
    runtime: static
    rootDir: tp01
    staticPublishPath: .

  - type: web
    name: tp02-fruhauf-ewan
    runtime: static
    rootDir: Front
    buildCommand: npm install && npm run build
    staticPublishPath: dist/front/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html